theme: jekyll-theme-cayman
title: "Instagram Download Scripts by Micha Birklbauer"
description: "Project Website for Instagram Downloader"
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instagram_downloader/archive/master.zip
  tar_url: https://github.com/t0xic-m/instagram_downloader/archive/master.tar.gz
