theme: jekyll-theme-minimal
title: "Instagram Downloader by Micha Birklbauer"
description: "Project Website for Instagram Downloader"
logo: https://raw.githubusercontent.com/michabirklbauer/projects/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/michabirklbauer/instagram_downloader/archive/master.zip
  tar_url: https://github.com/michabirklbauer/instagram_downloader/archive/master.tar.gz
